<?php
$conf['width']='50%';
$conf['height']='50%';
$conf['name']='Organigram';
$conf['archive']='./lib/plugins/orgapp/OrgApplet.jar';
$conf['code']='OrganigramApplet.class';
$conf['target']='_blank';
$conf['type']=0;
?>