<?php
$meta['width']=array('string');
$meta['height']=array('string');
$meta['name']=array('string');
$meta['archive']=array('string');
$meta['code']=array('string');
$meta['target']=array('string');
$meta['type']=array('numeric');
?>